name: cielo_flutter
description: Cielo/Braspag SDK for Flutter
version: 0.0.1
repository: https://github.com/romatallinn/cieloSdk-flutter

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
